# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
    # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '390f1bbb-90b8-4d01-929b-610002ab3164'
  # Web app name
  webAppName: 'backendcaio'
  # SolutionPath
  SolutionPath: '**/Gol-API/Gol-API.csproj'
  SolutionMigrationPath: './Infra.Data/'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: 'dotnet tool install --global dotnet-ef'
  displayName: Install dotnet EF
  
- script: 'cd $(SolutionMigrationPath) dotnet ef database update'
  displayName: Run Migration
- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: publish
    publishWebProjects: False
    projects: $(SolutionPath)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: $(azureServiceConnectionId)
    appName: $(webAppName)
    appType: 'webApp'
    package: $(Build.ArtifactStagingDirectory)/**/*.zip
